[package]
name = "nvim-sys"
version = "0.9.2"
edition = "2021"

[dependencies]
rmp = "0.8"
thiserror = "1.0"

[build-dependencies]
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
